# Generated by Django 4.1.2 on 2022-10-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTasks', '0002_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
